### ISSUE TITLE
central and local policy export/import

### ISSUE THREAD

**Issue by dvcraig88** [CiscoDevNet/sd-wan-ansible-pipeline-code#4]
Have you guys worked on any yml files for exporting and importing policies?  I am stuck on this and don't understand enough ansible yet. I tried making sense of the py files in the roles directory and comparing what was done for template export but they are built quite differently.

**Comment by jasonking3** [comment]
Steven recently setup a new [repo](https://github.com/ciscodevnet/sdwan-ops) that includes policy import/export.
