### ISSUE TITLE
sftp transfer mechanism failed on vEdge

### ISSUE THREAD

**Issue by fadervis** [CiscoDevNet/sd-wan-ansible-pipeline-code#5]
Hi Experts,

I'm stuck in the vEdge deployment phase (ansible-playbook configure.yml --tags=edge). Everything worked, apart form the vEdge part.

I got this error, can somebody please help me?

TASK [ansible-viptela : set_fact] ******************************************************************************************************************************************************************************************
ok: [vedge1]

TASK [ansible-viptela : Copy Root CA] **************************************************************************************************************************************************************************************
 [WARNING]: sftp transfer mechanism failed on [172.16.1.150]. Use ANSIBLE_DEBUG=1 to see detailed information

fatal: [vedge1]: FAILED! => {"changed": false, "checksum": "cce348c8368f55c8d99a8508ec271a20f0dff098", "module_stderr": "Shared connection to 172.16.1.150 closed.\r\n", "module_stdout": "fips_md.c(147): OpenSSL internal error, assertion failed: Digest update previous FIPS forbidden algorithm error ignored\r\n/bin/sh: line 1: 28340 Aborted                 (core dumped) /usr/bin/python /tmp/ansible/admin/ansible-tmp-1568643426.690371-122737129041527/AnsiballZ_copy.py\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 134}

NO MORE HOSTS LEFT *********************************************************************************************************************************************************************************************************
        to retry, use: --limit @/home/ansible/sd-wan-ansible-pipeline-code/configure.retry
<img width="1466" alt="ScreenCapture at Mon Sep 16 16:14:54 CEST 2019" src="https://user-images.githubusercontent.com/25461871/64965799-ef6eec80-d89d-11e9-8cae-5250d685d871.png">
<img width="1460" alt="ScreenCapture at Mon Sep 16 16:17:51 CEST 2019" src="https://user-images.githubusercontent.com/25461871/64965807-f269dd00-d89d-11e9-97ab-bbfecf4b1984.png">

**Comment by jasonking3** [comment]
I noticed that you were active on the WebEx Teams space and it appears that the issues was related to using version 19.2 of the Viptela components vs. 18.4.3.  For now this repo is only tested against 18.4.3 but we will be updating for 19.2.
